name: reminder
description: "\"Reminder\" is always with you when you need it!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

# Icons
  cupertino_icons: ^1.0.8

# State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  freezed_annotation: ^3.1.0
  freezed: ^3.2.3
  fpdart: ^1.2.0
  get_it: ^8.2.0

# HTTP Networking
  dio: ^5.9.0
  logger: ^2.6.2

# Storage management
  get_storage: ^2.1.1

# UI
  intl: ^0.20.2
  flutter_locales: ^3.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1


flutter:
  uses-material-design: true


  assets:
  # Logo & Splash
    - assets/dev/

  # Images & Icons
    - assets/dev/

  # Animations
    - assets/animations/

  # Audios
    - assets/audio/

  # Locales
    - assets/locales/
    - assets/locales/en.json
    - assets/locales/ru.json
    - assets/locales/uz.json

 

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  

