name: reminder
description: "\"Reminder\" is always with you when you need it!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

# Icons
  cupertino_icons: ^1.0.8

# State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  freezed_annotation: ^3.1.0
  freezed: ^3.2.3
  fpdart: ^1.2.0
  get_it: ^8.2.0

# HTTP Networking
  dio: ^5.9.0
  logger: ^2.6.2

# Storage management
  get_storage: ^2.1.1

# UI
  intl: ^0.20.2
  flutter_locales: ^3.0.3
  package_info_plus: ^9.0.0
  in_app_review: ^2.0.11
  url_launcher: ^6.3.2
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1


flutter:
  uses-material-design: true


  assets:
  # Logo & Splash
    - assets/dev/

  # Audios
    - assets/audio/

  # Animations
    - assets/animations/    

  # Images & Icons
    - assets/images/
    - assets/images/home/
    - assets/images/setting/
    - assets/images/calendar/

  # fonts
    - assets/fonts/
    - assets/fonts/poppins/
    - assets/fonts/roboto/

  # Locales
    - assets/locales/
    - assets/locales/en.json
    - assets/locales/ru.json
    - assets/locales/uz.json

 

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-SemiBold.ttf
          weight: 900

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 900

    - family: Playfair
      fonts:
        - asset: assets/fonts/playfair/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/playfair/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/playfair/PlayfairDisplay-SemiBold.ttf
          weight: 900    

    - family: PT_Sans_Narrow
      fonts:
        - asset: assets/fonts/pt_sans/PTSansNarrow-Regular.ttf
        - asset: assets/fonts/pt_sans/PTSansNarrow-Regular.ttf
          style: italic
        - asset: assets/fonts/pt_sans/PTSansNarrow-Bold.ttf
          weight: 900    

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 900                        
            


  
  

